# Generated by Django 3.2.4 on 2021-06-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_django_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likequestions',
            unique_together={('question', 'user')},
        ),
    ]
