# Generated by Django 3.2.4 on 2021-06-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_likequestions_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likequestions',
            name='mark',
            field=models.IntegerField(default=1, verbose_name='Mark'),
        ),
    ]
