# Generated by Django 3.2.4 on 2021-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='likequestions',
            name='mark',
            field=models.IntegerField(default=1),
        ),
    ]
